language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: m5nSnsIhU7ljQ0XzCGRPZO599KLcVeNjk8f3Ycv+Dn7+pBjEVF8AVxugxOG6k1mmo9iivR0Q92C3pfcCYURxa94NOi077b0F4fEU4kr8/+q1/DMsy093YH4dkcrSG3RmAXdh1oGQOTrnQ79l0a3SsH2DRVgSyYLWUlzfuTAm0as9GiglSnDxLPVdlQPaAaIww2uOleJwGH4EAHj8MX3jLrSGzJKBw2XHr2R385EVb/YRBxyEq1Pj26VcnNQ42CQPnYzdCVb822JBIO6g/clmpqGz3UfB84ugbKTkAamymAwZ0F8/rqbDihyu/JM5bbUUf+EHR/cpHc8mI9ODJruuyFPWw365TeYkm35xzg7bSAIojwRIWhq/SIGePCGxj3YGujqKNycZ45wqR9PqVpUfe+cpesOXF+PxGHEZbnwfl80tGM56sGCZNW4Ois1UBV4UF37zP9O2bXNh2d9h1NDF82CH/EiCWjxCKAFmAPGaB2cO2uIjbVNY/QloSTxIjG0x5R/znPx2GxtP/cIXqeiirgblcZbUO0TMFKTKURddSrao0Y6U+Nhq7F73B5iUp8Xq/QjZ0oxoJnUtZkfuM2dBgAYderhmtGhcLoE4PY1HF0Vl+axopDBFxbTlq1TGC2pAGhVehhcaK3TCWbdpBBGIX2D7jJs9i2MvGPrXb7tJONc=
  - secure: I0nxGsTBMshpKc4dhOOalJ1tudf0CbtKWUavqkvKreXq/dj08TQ+7QJygctJ0DyRB05C30s07bJasC9edbb0lcVDVGnx/pfFQzQ8ZuVb47+Z3gr+8jrHhEIew0QckIsJP8i71XjWuwEWvtXr0YifdFaL8pOfHm5LpooMptCuNudDZ3zz4SpcSa3FCcU9z1Bbbelqk3ITBh2WSC0m67Ym2KCAywVIxC5Zm3Is6Olb7mYI5cjwxY8nzxunxMeourOECbeNv6Cn07ewpN7AcDeFIDfHU7D/sYUCILiw/pn0l2esjloU8h+k4VnXsP3wtYYnStm2SqNdZvJhihaG730hxk82q6yQc5mzMTMl3K7Br+XVHm6sM8Au65MDTS2Y9eeQcBbgZ/yrXovzD+O2P4g3+tN3f8uMcyTOGvlLOPuvzed3Y24iZGbkQyLHOA1fXno6tlEp3OdSN+WXSUop9txyZSkeeS+fTa9yn6OP72thuAymgoqZpXiERRCfdzaYe553MCr1/gK1vAgp0iS61GcANDRmEGFe9ffNn9As9g2INoTLKGQsi7JBea4OMvRidsqpVU4Pb1qxpZqQqWDQHsdQgXWDmlXj4liXQjSSxzH0Q50V6sQ9siq1Ln4p+UCH3+9dERS3h+i9ophCqXhCZonVr9yVLvCibA+9v4ZwXHdfq1U=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
